Repository GSG-G8/courses-search, pull requests merged in 2020-06, with the labels that each got.

#6 file structure
  .gitignore
  .travis.yml
  .vscode/settings.json
  __test__/index.test.js
  __test__/sum.js
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App/App.css
  client/src/App/index.js
  client/src/assets/icons/index.js
  client/src/assets/images/index.js
  client/src/components/CourseCard/index.js
  client/src/components/CourseCard/style.css
  client/src/components/index.js
  client/src/constants/router.js
  client/src/container/DetailsPage/index.js
  client/src/container/DetailsPage/style.css
  client/src/container/FavoritePage/index.js
  client/src/container/FavoritePage/style.css
  client/src/container/HomePage/index.js
  client/src/container/HomePage/style.css
  client/src/index.css
  client/src/index.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/errorHandle/index.js
  server/controllers/index.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/config/fakeData.js
  server/database/queries/index.js
  server/index.js
  server/routes/course.js
  server/routes/index.js
  server/utils/index.js
  server/utils/validation/index.js
Labels: awaiting review

#8 Add the readme content
  README.md
Labels: On progress

#9 eslint init
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  package-lock.json
  package.json
  server/.eslintrc.js
  server/__test__/index.test.js
  server/__test__/sum.js
  server/package-lock.json
  server/package.json
Labels: awaiting review

#10 7 install modules
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controllers/errorHandle/index.js
  server/src/controllers/index.js
  server/src/database/config/build.js
  server/src/database/config/build.sql
  server/src/database/config/connection.js
  server/src/database/config/fakeData.js
  server/src/database/queries/index.js
  server/src/index.js
  server/src/routes/course.js
  server/src/routes/index.js
  server/src/utils/index.js
  server/src/utils/validation/index.js
Labels: awaiting review

#12 Express Setup
  package.json
  server/package.json
  server/src/app.js
  server/src/index.js
  server/src/routes/index.js
Labels: awaiting review

#14 database
  server/src/database/config/build.js
  server/src/database/config/build.sql
  server/src/database/config/connection.js
  server/src/database/config/fakeData.js
Labels: Database, Done

#17 16 modify database and insert data to category table
  server/src/database/config/build.sql
  server/src/database/config/category.sql
Labels: Database, Done

#25 Handling error
  package-lock.json
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/controllers/errorHandle/index.js
  server/src/controllers/index.js
  server/src/controllers/routes/index.js
  server/src/database/config/connection.js
  server/src/router/index.js
  server/src/routes/index.js
Labels: Back-end, Done

#31 27 get favorite
  .gitignore
  package-lock.json
  package.json
  server/.gitignore
  server/__test__/index.test.js
  server/__test__/queries/getFavoriteCourse.test.js
  server/__test__/queries/getUserById.test.js
  server/__test__/routes/getFavoriteCourses.test.js
  server/__test__/sum.js
  server/package-lock.json
  server/package.json
  server/src/controllers/index.js
  server/src/controllers/middleware/getFavorite.js
  server/src/controllers/routes/index.js
  server/src/database/config/build.js
  server/src/database/config/connection.js
  server/src/database/config/fakeData.sql
  server/src/database/queries/getFavoriteCourse.js
  server/src/database/queries/getUserById.js
  server/src/database/queries/index.js
  server/src/router/index.js
  server/src/utils/index.js
  server/src/utils/validation/generalSchema.js
  server/src/utils/validation/index.js
Labels: Back-end route, awaiting review

#30 coursera api
  server/src/controllers/coursera/categories.json
  server/src/controllers/coursera/getCourses.js
  server/src/controllers/index.js
  server/src/database/config/build.sql
  server/src/database/queries/index.js
  server/src/database/queries/insertCourses.js
Labels: Back-end, awaiting review

#26 15-udemy data
  server/src/controllers/getUdemyData/index.js
  server/src/database/config/build.sql
  server/src/database/queries/addUdemyCourse.js
  server/src/database/queries/index.js
Labels: Database, awaiting review

#21 get courses
  server/__test__/queries/getFavoriteCourse.test.js
  server/__test__/routes/course.test.js
  server/__test__/routes/getFavoriteCourses.test.js
  server/package.json
  server/src/controllers/index.js
  server/src/controllers/middleware/getCatcourses.js
  server/src/database/config/connection.js
  server/src/database/config/fakeData.sql
  server/src/database/queries/catCourses.js
  server/src/database/queries/index.js
  server/src/router/index.js
Labels: Back-end route, awaiting review

#20 Scraping the data
  .gitignore
  server/package-lock.json
  server/src/controllers/scraping/categoryId.js
  server/src/controllers/scraping/index.js
  server/src/database/queries/addFutureCourses.js
  server/src/database/queries/index.js
Labels: Back-end, awaiting review

#28 get course details
  server/__test__/routes/getCourseDetails.test.js
  server/src/controllers/index.js
  server/src/controllers/middleware/getCourseDetails.js
  server/src/database/queries/courseDetails.js
  server/src/database/queries/index.js
  server/src/router/index.js
  server/src/routes/index.js
  server/src/utils/index.js
  server/src/utils/validation/generalSchema.js
  server/src/utils/validation/index.js
Labels: Back-end route, On progress

#39 insertCourses test
  server/__test__/queries/insertCourses.test.js
Labels: Back-end route, Test

#36 Get top rated courses
  server/__test__/routes/topCourses.test.js
  server/src/controllers/index.js
  server/src/controllers/middleware/getTopRatedCourses.js
  server/src/controllers/scraping/courses.json
  server/src/database/config/fakeData.sql
  server/src/database/queries/getTopCourses.js
  server/src/database/queries/index.js
  server/src/router/index.js
  server/src/routes/index.js
Labels: Back-end route, awaiting review

#40 General search
  server/__test__/routes/search.test.js
  server/src/app.js
  server/src/controllers/index.js
  server/src/controllers/middleware/searchCourses.js
  server/src/database/queries/index.js
  server/src/database/queries/searchCourses.js
  server/src/router/index.js
  server/src/utils/index.js
  server/src/utils/validation/generalSchema.js
  server/src/utils/validation/index.js
Labels: Back-end route, On progress

#41 37 google login
  client/src/App/index.js
  server/__test__/routes/getFavoriteCourses.test.js
  server/package-lock.json
  server/package.json
  server/src/controllers/getFavorite/index.js
  server/src/controllers/getUdemyData/index.js
  server/src/controllers/googleLogin/index.js
  server/src/controllers/index.js
  server/src/controllers/logout/index.js
  server/src/controllers/middleware/getCatcourses.js
  server/src/controllers/middleware/getCourseDetails.js
  server/src/controllers/middleware/getTopRatedCourses.js
  server/src/controllers/middleware/index.js
  server/src/controllers/middleware/searchCourses.js
  server/src/controllers/verifyUser/index.js
  server/src/database/queries/addUserData.js
  server/src/database/queries/index.js
  server/src/router/index.js
Labels: Back-end, awaiting review

#44 fix bug in page not found for protected routes
  server/__test__/routes/getFavoriteCourses.test.js
  server/src/router/index.js
Labels: awaiting review, bug

#34 add to favorite route
  server/__test__/queries/addFavorite.test.js
  server/__test__/queries/deleteFavorite.test.js
  server/__test__/routes/addFavorite.test.js
  server/__test__/routes/deleteFavorite.test.js
  server/__test__/routes/getFavoriteCourses.test.js
  server/src/controllers/coursera/getCourses.js
  server/src/controllers/favorite/add.js
  server/src/controllers/favorite/delete.js
  server/src/controllers/index.js
  server/src/database/queries/favorite/add.js
  server/src/database/queries/favorite/delete.js
  server/src/database/queries/index.js
  server/src/router/index.js
Labels: Back-end route, awaiting review

#49 Create react router
  client/src/App/index.js
  client/src/constants/router.js
  client/src/container/DetailsPage/index.js
  client/src/container/FavoritePage/index.js
  client/src/container/HomePage/index.js
Labels: Done, awaiting review

#48 fix course details query
  server/__test__/queries/getUserById.test.js
  server/__test__/routes/getCourseDetails.test.js
  server/src/controllers/getFavorite/index.js
  server/src/controllers/middleware/getCourseDetails.js
  server/src/database/config/fakeData.sql
  server/src/database/queries/courseComment.js
  server/src/database/queries/getUserById.js
  server/src/database/queries/index.js
  server/src/utils/validation/generalSchema.js
Labels: awaiting review, bug

#51 50 favorite folders
  server/__test__/queries/addCourseToFolderQuery.test.js
  server/__test__/queries/addFavoriteFolderQuery.test.js
  server/__test__/queries/checkUserFolder.test.js
  server/__test__/queries/deleteCourseFromFolderQuery.test.js
  server/__test__/queries/deleteFavoriteFolderQuery.test.js
  server/__test__/queries/editFavoriteFolderQuery.test.js
  server/__test__/queries/getFavoriteCourse.test.js
  server/__test__/routes/addFavoriteFolder.test.js
  server/__test__/routes/deleteFavoriteFolder.test.js
  server/__test__/routes/editFavoriteFolder.test.js
  server/__test__/routes/getFavoriteCourses.test.js
  server/__test__/routes/removeCourseFromFolder.test.js
  server/__test__/routes/updateCourseToFolder.test.js
  server/src/controllers/favoriteFolder/addFavoriteFolder/index.js
  server/src/controllers/favoriteFolder/deleteFavoriteFolder/index.js
  server/src/controllers/favoriteFolder/editFavoriteFolder/index.js
  server/src/controllers/favoriteFolder/index.js
  server/src/controllers/favoriteFolder/removeCourseFromFolder/index.js
  server/src/controllers/favoriteFolder/updateCourseToFolder/index.js
  server/src/controllers/index.js
  server/src/database/config/build.sql
  server/src/database/config/fakeData.sql
  server/src/database/queries/checkUserFolder.js
  server/src/database/queries/favorite/getFavoriteCourse.js
  server/src/database/queries/favoriteFolder/addCourseToFolderQuery.js
  server/src/database/queries/favoriteFolder/addFavoriteFolderQuery.js
  server/src/database/queries/favoriteFolder/deleteCourseFromFolderQuery.js
  server/src/database/queries/favoriteFolder/deleteFavoriteFolderQuery.js
  server/src/database/queries/favoriteFolder/editFavoriteFolderQuery.js
  server/src/database/queries/favoriteFolder/index.js
  server/src/database/queries/index.js
  server/src/router/index.js
  server/src/utils/index.js
  server/src/utils/validation/generalSchema.js
  server/src/utils/validation/index.js
Labels: Back-end, awaiting review

#47 landing page
  client/.eslintrc.js
  client/package.json
  client/src/App/index.js
  client/src/assets/categories.js
  client/src/container/HomePage/index.js
  client/src/container/HomePage/style.css
  client/src/index.js
  server/__test__/routes/course.test.js
  server/__test__/routes/topCourses.test.js
  server/src/controllers/index.js
  server/src/controllers/middleware/getCatcourses.js
  server/src/controllers/middleware/searchCourses.js
  server/src/database/queries/getTopCourses.js
  server/src/database/queries/searchCourses.js
  server/src/router/index.js
  server/src/utils/validation/generalSchema.js
  server/src/utils/validation/index.js
Labels: React Component, awaiting review

#53 Get category courses
  client/.eslintrc.js
  client/public/index.html
  client/src/App/index.js
  client/src/container/HomePage/index.js
  package-lock.json
  package.json
  server/src/controllers/middleware/getTopRatedCourses.js
Labels: awaiting review
