Repository GSG-G8/courses-search, pull requests merged in 2020-07, with the labels that each got.

#56 course details page
  client/.eslintrc.js
  client/src/App/index.js
  client/src/assets/images/defaultUser.png
  client/src/assets/images/index.js
  client/src/components/Login/index.js
  client/src/components/index.js
  client/src/container/DetailsPage/functions.js
  client/src/container/DetailsPage/index.js
  client/src/container/DetailsPage/style.css
  client/src/index.css
  server/src/controllers/errorHandle/index.js
Labels: Front, React Component, awaiting review

#62 52 favorite page
  client/.eslintrc.js
  client/src/container/FavoritePage/index.js
  client/src/container/FavoritePage/style.css
  server/__test__/routes/getFavoriteFolder.test.js
  server/src/controllers/errorHandle/index.js
  server/src/controllers/favoriteFolder/getFavoriteFolder.js
  server/src/controllers/getFavorite/index.js
  server/src/controllers/getUdemyData/index.js
  server/src/router/index.js
Labels: Front, awaiting review

#64 auth context
  client/src/App/index.js
  client/src/constants/router.js
  client/src/container/DetailsPage/index.js
  client/src/container/authContext.js
Labels: Done, Front-End Routes

#67 add signOut option
  client/src/components/Login/index.js
  client/src/container/DetailsPage/functions.js
  client/src/container/DetailsPage/index.js
  client/src/container/authContext.js
  server/__test__/routes/getCourseDetails.test.js
  server/src/controllers/comment/add.js
  server/src/controllers/googleLogin/index.js
  server/src/database/config/build.sql
  server/src/database/queries/addUserData.js
  server/src/database/queries/comment/add.js
  server/src/database/queries/courseComment.js
Labels: Front, awaiting review

#68 Footer component
  client/src/App/App.less
  client/src/App/index.js
  client/src/assets/icons/Home.svg
  client/src/assets/icons/Logo.js
  client/src/components/common/footer/index.js
  client/src/components/common/footer/style.css
  client/src/container/HomePage/index.js
Labels: TL-Approved

#78 main page style
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App/App.less
  client/src/assets/images/Image.png
  client/src/assets/images/index.js
  client/src/components/common/footer/index.js
  client/src/components/common/footer/style.css
  client/src/container/HomePage/index.js
  client/src/container/HomePage/style.css
  server/src/database/queries/searchCourses.js
Labels: awaiting review

#77 fix login logic
  client/src/App/index.js
  client/src/App/protectedRoute.js
  client/src/container/authContext.js
  server/src/controllers/errorHandle/index.js
  server/src/database/queries/addUserData.js
Labels: Front, awaiting review

#75 Main page design
  client/src/assets/courseCategories.js
  client/src/container/HomePage/index.js
  client/src/container/HomePage/style.css
  server/src/controllers/errorHandle/index.js
  server/src/controllers/scraping/index.js
Labels: On progress

#82 show category name
  client/src/container/FavoritePage/index.js
  client/src/container/FavoritePage/style.css
  client/src/container/HomePage/index.js
  client/src/container/HomePage/style.css
Labels: Front

#84 show comment date
  client/src/container/DetailsPage/index.js
  server/__test__/routes/getCourseDetails.test.js
  server/src/database/config/build.sql
  server/src/database/queries/courseComment.js
Labels: Back-end, Front
